web:
  build: .
  command: bin/web
  environment:
    - PORT=3000
    # uncomment and remove from bin/web when this lands: https://github.com/docker/compose/pull/1765
    #- "DYNO=web.${HOSTNAME}"
  ports:
    - 80:3000

